import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const source = (path) => readFile(new URL(path, root), "utf8");

test("Inicio conserva bandeja, acciones contextuales y elección IA/demo", async () => {
  const page = await source("app/page.tsx");
  assert.match(page, /Entiende tus finanzas/);
  assert.match(page, /Tienes \{visibleCards\.length/);
  assert.match(page, /Disney\+ aparece dos veces/);
  assert.match(page, /Tu tarjeta tiene restaurantes con descuento/);
  assert.match(page, /CUENTAS COMPARTIDAS/);
  assert.match(page, /Tienes cuentas sin cerrar/);
  assert.doesNotMatch(page, /Le debes a Camila/);
  assert.match(page, /La cuenta de Liguria parece compartida/);
  assert.match(page, /Pregúntale a YOL1/);
  assert.match(page, /Usar IA/);
  assert.match(page, /Seguir en demo/);
  assert.match(page, /Ignorar/);
  assert.match(page, /Dividir en Cuentas Claras/);
  assert.match(page, /carousel-dots/);
  assert.match(page, /Deshacer última/);
  assert.match(page, /Se guarda para revisión por parte del equipo creador/i);
  assert.doesNotMatch(page, /Explorar ejemplo|Simular con mi información/);
  assert.doesNotMatch(page, /Micrófono de demo/);
});

test("la IA opera server-side con consentimiento, límites y fallback", async () => {
  const page = await source("app/page.tsx");
  const route = await source("app/api/chat/route.ts");
  const prompt = await source("lib/ai/yol1-prompt.ts");
  const knowledge = await source("lib/ai/knowledge.ts");
  const envExample = await source(".env.example");
  const evals = JSON.parse(await source("evals/yol1-cases.json"));
  assert.match(route, /process\.env\.OPENAI_API_KEY/);
  assert.match(route, /typedBody\.aiConsent !== true/);
  assert.match(route, /MAX_MESSAGES = 12/);
  assert.match(route, /MAX_MESSAGE_LENGTH = 700/);
  assert.match(route, /store: false/);
  assert.match(route, /api\.openai\.com\/v1\/responses/);
  assert.match(route, /createDemoResponse/);
  assert.doesNotMatch(page, /OPENAI_API_KEY|api\.openai\.com|Authorization:|Bearer /);
  assert.match(prompt, /No solicites claves/);
  assert.match(prompt, /Una coincidencia no es una conclusión/);
  assert.match(knowledge, /YOL1_KNOWLEDGE_VERSION/);
  assert.match(envExample, /OPENAI_API_KEY=\s*$/m);
  assert.doesNotMatch(envExample, /sk-[A-Za-z0-9]/);
  assert.ok(evals.length >= 4);
});

test("el conocimiento aprobado se resuelve antes de pedir IA", async () => {
  const route = await source("app/api/chat/route.ts");
  const catalog = await source("lib/ai/knowledge-catalog.ts");
  const router = await source("lib/ai/knowledge-router.ts");
  const viewer = await source("app/review/knowledge/page.tsx");
  const css = await source("app/globals.css");
  const index = await source("knowledge/INDEX.md");
  const workflow = await source("knowledge/WORKFLOW-POR-VOZ.md");
  assert.match(route, /routeKnowledge\(lastQuestion\)/);
  assert.ok(route.indexOf("localRoute.kind") < route.indexOf('fetch("https://api.openai.com/v1/responses"'), "el router local debe ejecutarse antes de la API");
  assert.match(router, /Qué veo:/);
  assert.match(router, /Qué significa:/);
  assert.match(router, /Qué puedes hacer ahora:/);
  assert.match(router, /No voy a inventar una respuesta/);
  assert.match(router, /calculateLabMonthResult/);
  assert.match(catalog, /lab-kb-2026-08-26\.3/);
  assert.match(index, /collect-receivables-001/);
  assert.match(workflow, /Felipe dicta/);
  assert.match(viewer, /Conocimiento del Lab/);
  assert.match(viewer, /Marcar para mejorar/);
  assert.match(viewer, /localStorage/);
  assert.doesNotMatch(viewer, /fetch\(|github|OPENAI_API_KEY/i);
  assert.match(css, /@media \(max-width:800px\)[\s\S]*\.knowledge-overview/);
  assert.match(css, /\.knowledge-answer,\.knowledge-columns \{ grid-template-columns:1fr/);
});

test("feedback y respuestas llegan a una bandeja editorial con fallback local", async () => {
  const page = await source("app/page.tsx");
  const review = await source("app/review/page.tsx");
  const readme = await source("README.md");
  const adapter = await source("lib/learning-review.ts");
  const sharedClient = await source("lib/shared-feedback-client.ts");
  const architecture = await source("AI-ARCHITECTURE.md");
  assert.match(page, /Útil/);
  assert.match(page, /Mejoraría/);
  assert.match(page, /localChatFeedbackIntake\.submit/);
  assert.match(page, /submitChatResponse/);
  assert.match(review, /Bandeja de aprendizaje/);
  assert.match(review, /Feedbacks e ideas/);
  assert.match(review, /Propuestas que toman forma/);
  assert.match(review, /Entrenamiento IA/);
  assert.match(review, /Por evaluar/);
  assert.match(review, /Listos para aprender/);
  assert.match(review, /Evaluar/);
  assert.match(review, /Después/);
  assert.match(review, /Archivar/);
  assert.doesNotMatch(review, /Convertido en mejora, guía o proyecto/);
  assert.match(readme, /Para después, Resuelto o Ignorado/);
  assert.doesNotMatch(readme, /Para después, Convertido o Ignorado/);
  assert.match(review, /Respuestas que pueden mejorar el criterio del equipo/);
  assert.match(review, /Tu lectura/);
  assert.match(review, /MODO LOCAL · AÚN NO COMPARTIDO/);
  assert.match(review, /<DecisionInbox \/>/);
  assert.doesNotMatch(review, /example:(?:feedback|prototype):remesas/);
  assert.doesNotMatch(review, /feedback sobre remesas/i);
  assert.match(review, /window\.localStorage\.setItem\("yol1-lab-theme", next\)/);
  assert.match(review, /button onClick=\{chooseTheme\}/);
  assert.match(adapter, /localStorage/);
  assert.doesNotMatch(adapter, /fetch\(|github\.com|api\.github/i);
  assert.match(sharedClient, /fetch\("\/api\/feedback"/);
  assert.doesNotMatch(sharedClient, /DATABASE_URL|YOL1_REVIEW_TOKEN/);
  assert.match(architecture, /nunca reescribe automáticamente/i);
});

test("brief y ciclo QA conservan estados editoriales y alcance canónicos", async () => {
  const brief = await source("BRIEF-NOCHE-EJECUCION.md");
  const qaCycle = await source("QA-CICLO-TRIPLE.md");
  const productDesign = await source("PRODUCT-DESIGN.md");
  const onboardingPrd = await source("PRD-ONBOARDING-KYC-PROGRESIVO.md");
  const technicalStandard = await source("ESTANDAR-QA-TECNICO-PRD.md");
  const nightBoard = await source("TABLERO-NOCHE.md");
  const nightPlan = await source("PLAN-NOCHE-YOL1.md");
  const onboardingScope = brief.match(/## 3\. Onboarding y KYC progresivo[\s\S]*?(?=\n## 4\.)/)?.[0] ?? "";
  const remittancesScope = brief.match(/## 6\. Remesas[\s\S]*?(?=\n## 7\.)/)?.[0] ?? "";
  const confirmedDirection = brief.match(/## 10\. Dirección de producto confirmada por Felipe[\s\S]*?(?=\n## 11\.)/)?.[0] ?? "";
  const synthesis = brief.match(/## 11\. Síntesis de las tres auditorías[\s\S]*?(?=\n## 12\.)/)?.[0] ?? "";
  const priorities = qaCycle.match(/## Prioridades actuales[\s\S]*$/)?.[0] ?? "";
  const remittancesPlan = nightPlan.match(/### Remesas[\s\S]*?(?=\n### Construir mi propio producto)/)?.[0] ?? "";
  assert.match(onboardingScope, /acceso gradual gobernado por una capacidad aprobada/);
  assert.doesNotMatch(onboardingScope, /desbloqueo incremental según KYC, licencias y producto/);
  assert.match(remittancesScope, /Fuera de alcance hasta nueva instrucción de Felipe/);
  assert.match(remittancesScope, /No investigar, definir, diseñar ni prototipar/);
  assert.doesNotMatch(remittancesScope, /Solo investigación y definición/);
  assert.match(confirmedDirection, /KYC puede ser un requisito progresivo de una capacidad aprobada, pero nunca la habilita por sí solo/);
  assert.doesNotMatch(confirmedDirection, /KYC es una progresión que desbloquea capacidades/);
  assert.match(synthesis, /Nuevo, En revisión, Guardar para después, Resuelto e Ignorado/);
  assert.doesNotMatch(synthesis, /Guardar para después, Convertido e Ignorado/);
  assert.match(synthesis, /destino `mejora \/ guía Markdown \/ proyecto` sigue siendo una decisión aparte/);
  assert.match(priorities, /Remesas queda fuera de alcance hasta nueva instrucción/);
  assert.doesNotMatch(priorities, /Remesas queda en investigación/);
  assert.match(qaCycle, /Por cada pantalla implementada o propuesta que pase a revisión/);
  assert.match(qaCycle, /actualización de la especificación interna, PRD/);
  assert.doesNotMatch(qaCycle, /Por cada pantalla publicada|actualización de Ficha de producto/);
  assert.match(technicalStandard, /En los productos explorables, el Lab muestra una ficha resumida debajo de la composición/);
  assert.match(technicalStandard, /La ficha resumida se renderiza a ancho completo sólo para Acompañante, Onboarding y Builder/);
  assert.doesNotMatch(technicalStandard, /no la renderiza en la experiencia pública/);
  assert.doesNotMatch(technicalStandard, /Aplica a los productos publicados|El Lab ya expone una Ficha por pantalla/);
  assert.match(productDesign, /no se agregan diagonales ni triángulos decorativos al pie/);
  assert.match(productDesign, /Las fichas de producto se muestran debajo de la composición principal, a ancho completo, solo en los productos explorables/);
  assert.match(productDesign, /La ficha resume esa trazabilidad para la acción inspeccionada/);
  assert.doesNotMatch(productDesign, /no se expone como inspector público/);
  assert.match(productDesign, /Feedback permanece disponible en todos los espacios/);
  assert.match(onboardingPrd, /La especificación interna resume la regla crítica/);
  assert.doesNotMatch(productDesign, /Acid identifica el único producto publicado/);
  assert.doesNotMatch(productDesign, /La Ficha de producto vive debajo del teléfono/);
  assert.match(nightBoard, /borrador local en investigación/);
  assert.doesNotMatch(nightBoard, /borrador local no publicado/);
  assert.match(remittancesPlan, /Fuera de alcance: no abrir preguntas, research, diseño ni prototipos/);
  assert.doesNotMatch(remittancesPlan, /¿Quién envía|¿Qué dolor|¿Qué debe poder entender|¿Qué partner/);
  assert.doesNotMatch(nightPlan, /pantallas actuales, tanto local como la versión publicada/);
});

test("el registro nocturno conserva secciones consecutivas en orden", async () => {
  const brief = await source("BRIEF-NOCHE-EJECUCION.md");
  const sections = [...brief.matchAll(/^## (\d+)\./gm)].map((match) => Number(match[1]));
  assert.deepEqual(sections, Array.from({ length: sections.length }, (_, index) => index + 1));
});

test("intake compartido protege Postgres y la revisión privada", async () => {
  const route = await source("app/api/feedback/route.ts");
  const reviewAuth = await source("lib/server/review-auth.ts");
  const store = await source("lib/server/feedback-store.ts");
  const page = await source("app/page.tsx");
  const envExample = await source(".env.example");
  assert.match(reviewAuth, /YOL1_REVIEW_TOKEN/);
  assert.match(reviewAuth, /process\.env\.NODE_ENV === "development" \? "Yol1" : ""/);
  assert.match(route, /reviewConfigured: isReviewConfigured\(\)/);
  assert.doesNotMatch(reviewAuth, /YOL1_REVIEW_TOKEN \|\| "Yol1"/);
  assert.match(reviewAuth, /timingSafeEqual/);
  assert.match(route, /sameOrigin/);
  assert.match(route, /containsSensitiveData/);
  assert.match(route, /countRecentFeedback\(sessionHash\) >= 20/);
  assert.match(route, /status === "wrong" && !reviewNote/);
  assert.match(store, /process\.env\.DATABASE_URL/);
  assert.match(store, /CREATE TABLE IF NOT EXISTS yol1_feedback_items/);
  assert.match(store, /ON CONFLICT \(id\) DO UPDATE/);
  assert.match(store, /session_hash/);
  assert.doesNotMatch(page, /process\.env\.DATABASE_URL|YOL1_REVIEW_TOKEN|from ["']@neondatabase/);
  assert.match(envExample, /DATABASE_URL=\s*$/m);
  assert.match(envExample, /YOL1_REVIEW_TOKEN=\s*$/m);
  assert.doesNotMatch(envExample, /postgres(?:ql)?:\/\/[^\s]+:[^\s]+@/i);
});

test("acciones y confirmaciones permanecen simuladas y visibles", async () => {
  const page = await source("app/page.tsx");
  const clearAccounts = await source("app/cuentas-claras/page.tsx");
  const payer = await source("app/pagar/[token]/page.tsx");
  const provider = await source("lib/debt-center/floid-provider.ts");
  const css = await source("app/globals.css");
  assert.match(page, /phone-toast/);
  assert.match(css, /\.phone-toast/);
  assert.match(clearAccounts, /SIMULACIÓN · NO MUEVE DINERO/);
  assert.match(clearAccounts, /Nada se enviará automáticamente/);
  assert.match(payer, /SIMULACIÓN · NO MUEVE PLATA/);
  assert.match(provider, /new MockFloidPaymentProvider\(\)/);
  assert.doesNotMatch(provider, /fetch\(|FLOID_API|process\.env/);
  assert.match(clearAccounts, /SIN BANCO CONECTADO/);
  const surfacesWithoutExplicitDenials = `${page}\n${clearAccounts}\n${payer}`.replaceAll("SIN BANCO CONECTADO", "");
  assert.doesNotMatch(surfacesWithoutExplicitDenials, /dinero transferido|banco conectado/i);
});

test("Cartola usa navegación general e individual y acciones coherentes", async () => {
  const page = await source("app/page.tsx");
  assert.match(page, /Ver cartola general/);
  assert.match(page, /\["General", "BCI", "MACH"\]/);
  assert.match(page, /"Marcar revisado" \| "Revisar" \| "Dividir en Cuentas Claras" \| "Ver en Cuentas Claras"/);
  assert.match(page, /ASISTENTE DEMO/);
  assert.match(page, /Guardar nota del ejemplo/);
  assert.match(page, /Nota guardada/);
  assert.match(page, /Revisado/);
  assert.match(page, /movement-detail-meta/);
  assert.doesNotMatch(page, /\{movement\.bank\} · \{movement\.code\}/);
});

test("Acompañante entrega las cuentas compartidas al producto Cuentas Claras", async () => {
  const page = await source("app/page.tsx");
  const portfolio = await source("lib/product-portfolio.ts");
  assert.match(page, /new URLSearchParams\(\{ product: "clear_accounts"/);
  assert.match(page, /window\.location\.assign\(`\/\?\$\{params\.toString\(\)\}`\)/);
  assert.match(page, /Vas a abrir Cuentas Claras/);
  assert.match(page, /Ver en Cuentas Claras/);
  assert.match(page, /Dividir en Cuentas Claras/);
  assert.doesNotMatch(page, /tab === "cobrar" && <Collect/);
  assert.doesNotMatch(page, /label="Cobrar\/pagar"/);
  assert.match(portfolio, /id: "clear_accounts"/);
});

test("lenguaje cotidiano, navegación literal y estados de confianza quedan visibles", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  assert.match(page, /Te entró/);
  assert.match(page, /Gastaste/);
  assert.match(page, /Tu plan de deuda/);
  assert.match(page, /Deudas/);
  assert.doesNotMatch(page, /Gana más lucas/);
  assert.match(page, /Mi banco/);
  assert.match(page, /Feedback/);
  assert.match(page, /Claro/);
  assert.match(page, /Oscuro/);
  assert.match(css, /\.bottom-nav button>small[^}]*font-size:9px/i);
});

test("Ahorrar ordena la conclusión antes de la evidencia sin ocultar transparencia", async () => {
  const page = await source("app/page.tsx");
  assert.match(page, /Ver por qué/);
  assert.match(page, /Ignorar/);
  assert.match(page, /Recuperar última/);
  assert.match(page, /Puede convenirte/);
  assert.match(page, /Evidencia/);
  assert.match(page, /Certeza/);
  assert.match(page, /Disclosure/);
});

test("tema dual y acentos semánticos están tokenizados", async () => {
  const css = await source("app/globals.css");
  const design = await source("PRODUCT-DESIGN.md");
  assert.match(css, /\.lab-shell\[data-theme="dark"\]/);
  assert.match(css, /\.lab-shell\[data-theme="light"\]/);
  assert.match(css, /--neon-pink:#ff8fb4/i);
  assert.match(css, /--violet-soft:/i);
  assert.match(css, /\.collect-hero[^}]*box-shadow:[^}]*var\(--neon-pink\)/i);
  assert.match(css, /\.pending-actions button:nth-child\(2\)[^}]*background:var\(--neon-pink\)/i);
  assert.match(css, /\.movement\.selected[^}]*var\(--aqua\)/i);
  assert.match(design, /nunca error, alerta ni dato crítico/i);
});

test("documenta límites y gates de aprendizaje", async () => {
  const spec = await source("MVP-SPEC.md");
  assert.match(spec, /E2 — Comprensión/);
  assert.match(spec, /E3 — Acción voluntaria/);
  assert.match(spec, /E4 — Resultado \/ retorno/);
  assert.match(spec, /No demuestra demanda, product-market fit, economics ni readiness/i);
  assert.match(spec, /Directo y Embebido quedan fuera/i);
});

test("feedback conserva fallback local y permanece desacoplado de GitHub", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  const adapter = await source("lib/feedback-intake.ts");
  const architecture = await source("FEEDBACK-INTAKE.md");
  assert.match(page, /product=\{activeProduct\.name\} screen=\{activeTitle\} open=\{true\}/);
  assert.match(page, /key=\{`desktop-feedback-\$\{productId\}-\$\{activeTitle\}`\}/);
  assert.match(page, /key=\{`mobile-feedback-\$\{productId\}-\$\{activeTitle\}`\}/);
  assert.match(page, /variant="desktop" compact=\{false\}/);
  assert.match(page, /Me gusta/);
  assert.match(page, /Mejoraría/);
  assert.match(page, /Idea/);
  assert.match(page, /No incluyas datos financieros ni personales/);
  assert.doesNotMatch(page, /life-shot|yol1-life\.jpg/);
  assert.match(css, /\.feedback-desktop[^}]*position:static/i);
  assert.doesNotMatch(css, /\.feedback-desktop[^}]*position:absolute/i);
  assert.doesNotMatch(page, /className="module-map"/);
  assert.match(css, /@media \(max-width:720px\)[\s\S]*\.feedback-mobile\.feedback-open/i);
  assert.match(css, /inset:62px 8px 70px/i);
  assert.match(adapter, /localStorage/);
  assert.match(adapter, /FeedbackIntakeAdapter/);
  assert.doesNotMatch(adapter, /github\.com|api\.github|Authorization|Bearer/i);
  assert.match(architecture, /ruta server-side protegida|POST \/api\/feedback/i);
  assert.match(architecture, /branch \+ PR.*aprobación|branch\/PR.*aprobación/i);
});

test("portfolio mantiene siete productos y cuatro prototipos explorables", async () => {
  const page = await source("app/page.tsx");
  const portfolio = await source("lib/product-portfolio.ts");
  const css = await source("app/globals.css");
  const definitions = portfolio.match(/\{ id: "(?:companion|kyc|clear_accounts|banking|cards|remittances|builder)"/g) ?? [];
  assert.equal(definitions.length, 7);
  assert.match(portfolio, /name: "Acompañante financiero"[\s\S]*explorable: true/);
  assert.match(portfolio, /name: "Onboarding y KYC progresivo"/);
  assert.match(portfolio, /name: "Cuentas Claras"/);
  assert.match(portfolio, /name: "Home Banking"/);
  assert.match(portfolio, /name: "Tarjetas"/);
  assert.match(portfolio, /name: "Remesas"/);
  assert.match(portfolio, /name: "Construir mi propio producto"/);
  assert.equal((portfolio.match(/explorable: true/g) ?? []).length, 4);
  assert.equal((portfolio.match(/explorable: false/g) ?? []).length, 3);
  assert.doesNotMatch(portfolio, /published: (?:true|false)/);
  assert.doesNotMatch(portfolio, /flujo publicado|Especificaciones de producto publicadas/);
  assert.doesNotMatch(css, /productos publicados|experiencias publicadas/);
  assert.match(page, /EN INVESTIGACIÓN/);
  assert.doesNotMatch(page, /Volver al Acompañante financiero/);
  assert.match(portfolio, /EMPTY_STATE_LIBRARY[\s\S]*perro feliz que te hará compañía/i);
  assert.match(portfolio, /acá hay un gato tecleando/i);
  assert.match(portfolio, /Alguien no hizo la pega/i);
  assert.match(portfolio, /Remesas no está siendo trabajada ahora/i);
  assert.match(portfolio, /ChatGPT, Claude o Codex/);
  assert.match(portfolio, /Un robot está ordenando los post-its/i);
  assert.ok((portfolio.match(/gesture: "/g) ?? []).length >= 12);
  assert.doesNotMatch(portfolio, /eyebrow: "NO PUBLICADO"/);
  assert.match(page, /window\.scrollTo\(\{ top: 0, behavior: "auto" \}\)/);
  assert.match(css, /@keyframes dog-tail-wag/);
  assert.match(css, /@keyframes cat-type/);
  assert.match(css, /@keyframes robot-note-shuffle/);
  assert.doesNotMatch(page, /MCP conectado|banco conectado|KYC aprobado|remesa enviada/i);
});

test("la capa visual v2 permanece reversible y candidata", async () => {
  const layout = await source("app/layout.tsx");
  const css = await source("app/design-system.css");
  const crosswalk = await source("design-system/DESIGN-SYSTEM-CROSSWALK.md");
  assert.ok(layout.indexOf('import "./globals.css"') < layout.indexOf('import "./design-system.css"'));
  assert.match(layout, /<body className="yol1-system-v2">/);
  assert.match(crosswalk, /candidato implementado y versionado en el Product Lab/i);
  assert.match(crosswalk, /pendiente de aprobación visual de Felipe/i);
  assert.doesNotMatch(crosswalk, /pendiente de revisión visual de Felipe antes de commit/i);
  assert.match(css, /@media \(max-width: 390px\)[\s\S]*\.yol1-system-v2 \.review-header \{[\s\S]*grid-template-columns: 72px minmax\(0, 1fr\)/);
  assert.match(css, /\.yol1-system-v2 \.review-board-tabs button :where\(small, strong\)[\s\S]*overflow-wrap: anywhere/);
});

test("los contratos de producto se montan solo en productos explorables", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  const portfolio = await source("lib/product-portfolio.ts");
  const feedback = await source("lib/feedback-intake.ts");
  assert.match(page, /ProductSpecPanel/);
  assert.match(page, /FICHA DE PRODUCTO · PARA DESARROLLO/);
  assert.match(page, /activeProduct\.explorable && productId !== "builder" && <ProductSpecPanel/);
  assert.match(page, /productId === "builder" && sharedProjectState === "ready" && sharedProject && <div id="builder-technical-panel">/);
  assert.match(page, /setProductId\(next\);\s*setNotice\(""\);\s*setInspectedAction\(null\);\s*syncLabRoute\(next/);
  assert.match(page, /const hasEvent = Boolean\(inspectedAction \? inspectedAction\.eventId : spec\.event\)/);
  assert.match(page, /hasEvent \? inspectedEvent : "instrumentación pendiente"/);
  assert.match(css, /\.team-spec \{ grid-column:1\/-1; width:100%/);
  assert.doesNotMatch(page, /Felipe resuelve contradicciones|Estado de revisión/);
  assert.match(page, /onFocusCapture/);
  assert.match(page, /control\.closest\("\.phone"\)/);
  assert.match(page, /phone_control_interacted/);
  assert.match(page, /phone_field_interacted/);
  assert.match(page, /data-instrumentation-ignore="true"/);
  assert.match(page, /data-event-id="companion_navigation_selected"/);
  assert.match(page, /data-event-id="profile_menu_opened"/);
  assert.match(page, /data-event-id="theme_mode_toggled"/);
  assert.match(portfolio, /eventMetadata\(/);
  assert.match(portfolio, /user_id/);
  assert.match(portfolio, /event_at/);
  assert.match(portfolio, /product_key/);
  assert.match(portfolio, /screen_key/);
  assert.match(portfolio, /action_key/);
  assert.match(portfolio, /simpleEventName\(/);
  assert.match(portfolio, /data:\s*\{ store:/);
  assert.match(portfolio, /questions:/);
  assert.match(portfolio, /risks:/);
  assert.match(portfolio, /React Native/);
  assert.match(portfolio, /AWS/);
  assert.match(portfolio, /"No aplica" \| "Por validar" \| "Requerido"/);
  assert.match(portfolio, /Chile es la jurisdicción base/);
  assert.match(feedback, /product\?: string/);
  assert.doesNotMatch(page, /analytics\.track|gtag\(|mixpanel|segment\.track/i);
});

test("los productos en investigación no simulan una app ni muestran ficha técnica", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  assert.match(page, /productId === "companion" \|\| productId === "clear_accounts" \|\| productId === "kyc" \|\| productId === "builder"/);
  assert.doesNotMatch(page, /productId === "cards" && <CardsDiscovery/);
  assert.match(page, /TENGO UNA IDEA/);
  assert.doesNotMatch(page, /ProductSpecification|living-spec/);
  assert.match(page, /className="research-phone"/);
  assert.match(page, /className="research-halo"/);
  assert.match(css, /\.research-phone \{/);
  assert.match(css, /\.research-halo \{/);
  assert.match(css, /@media \(max-width:720px\)[\s\S]*\.research-stage \{[^}]*overflow-x:clip/);
  assert.doesNotMatch(page, /Unpublished|unpublished/);
  assert.doesNotMatch(css, /unpublished/);
});

test("el builder separa la conversación externa de la vista previa y el envío editorial", async () => {
  const page = await source("app/page.tsx");
  const knowledge = await source("knowledge/construir-mi-propio-producto.md");
  const builderPlan = await source("MCP-BUILDER-PLAN.md");
  const nightBoard = await source("TABLERO-NOCHE.md");
  const css = await source("app/globals.css");
  const outputContract = await source("BUILDER-OUTPUT-CONTRACT.md");
  const flowMap = await source("BUILDER-FLOW-MAP.md");
  const localIntake = await source("lib/feedback-intake.ts");
  const submitPanel = page.slice(page.indexOf("function ProjectSubmitPanel"), page.indexOf("function ResearchStage"));
  assert.match(page, /function ProjectBuilderScreen/);
  assert.match(page, /function BuilderOrientationPanel/);
  assert.match(page, /YOL1 revisa esto contigo/);
  assert.match(page, /FICHA DE PRODUCTO/);
  assert.match(page, /HECHOS CONOCIDOS/);
  assert.match(page, /APORTES DE LA PERSONA/);
  assert.match(page, /ENCAJE TECNOLÓGICO/);
  assert.match(page, /CONTINUIDAD YOL1/);
  assert.match(css, /\.builder-product-sheet/);
  assert.match(page, /Ver decisiones y base técnica/);
  assert.match(page, /Tu conversación no se sincroniza automáticamente/);
  assert.match(page, /Los artefactos viven en tu cliente/);
  assert.match(css, /\.builder-orientation[^}]*grid-column:1\/-1/);
  assert.match(css, /\.builder-example-tabs button[^}]*min-height:46px/);
  assert.match(page, /Tu idea entra acá[\s\S]*Tu producto empieza a tomar forma/);
  assert.match(page, /YOL1 no lee tu conversación/i);
  assert.match(page, /Ver guía para[\s\S]*ChatGPT/);
  assert.match(page, /Ver guía para[\s\S]*Claude/);
  assert.match(page, /Ver guía para[\s\S]*Codex/);
  assert.match(page, /MENSAJE LISTO PARA CHATGPT, CLAUDE O CODEX/);
  assert.match(page, /Piloto disponible/i);
  assert.match(page, /Cómo ocupar/);
  assert.match(page, /NEXT_PUBLIC_MCP_URL/);
  assert.match(page, /process\.env\.NEXT_PUBLIC_MCP_URL\?\.trim\(\) \|\| `\$\{YOL1_SITE_URL\}\/api\/mcp`/);
  assert.doesNotMatch(page, /YOL1_MCP_URL = process\.env\.NEXT_PUBLIC_MCP_URL \|\|/);
  assert.match(page, /Abrir la vista del Lab ahora/);
  assert.match(page, /No agregues argumentos, environment ni working directory/i);
  assert.match(page, /PEGA ESTA FRASE PARA ACTIVAR YOL1/);
  assert.match(page, /Activa YOL1 para construir un producto, sigue los pasos del MCP/);
  assert.match(page, /guide === "claude" \? "un chat nuevo en Cowork" : guide === "codex" \? "una tarea nueva" : "un chat nuevo"/);
  assert.match(page, /Después cuenta tu idea y sigue los pasos: YOL1 te irá guiando hasta una primera propuesta/);
  assert.doesNotMatch(page, /ejecuta yol1_start_builder antes de responder/i);
  assert.doesNotMatch(page, /revisar versiones, contar herramientas ni reconectar/i);
  assert.doesNotMatch(page, /Ejecuta yol1_start_builder, yol1_get_context y yol1_get_delivery_contract/);
  assert.match(page, /Propuesta revisable · no publicada/);
  assert.match(page, /data-event-id="builder_guide_viewed" data-client="chatgpt"/);
  assert.match(page, /data-event-id="builder_guide_viewed" data-client="claude"/);
  assert.match(page, /data-event-id="builder_guide_viewed" data-client="codex"/);
  assert.match(page, /Settings → MCP servers → Add server/);
  assert.match(page, /Elige Streamable HTTP/);
  assert.match(page, /No elijas STDIO ni pegues la URL en command/);
  assert.match(page, /Si comienza con https:\/\/, siempre va en URL/);
  assert.match(page, /Pulsa <b>Restart<\/b>/);
  assert.match(page, /abre <b>\/mcp<\/b> y confirma que YOL1 esté conectado/);
  assert.match(page, /\[mcp_servers\.yol1\][\s\S]*enabled = true[\s\S]*url =/);
  assert.doesNotMatch(page, /command = "\$\{YOL1_MCP_URL\}"/);
  assert.match(page, /Copiar configuración Codex/);
  assert.match(page, /RESULTADO ESPERADO/);
  assert.match(page, /YOL1 · conectado · 7 herramientas/);
  assert.match(page, /streamable_http/);
  assert.match(page, /Si ves <code>stdio<\/code> o una URL dentro de <code>command<\/code>/);
  assert.match(page, /codex mcp remove yol1[\s\S]*codex mcp add yol1 --url/);
  assert.match(page, /Copiar reparación segura/);
  assert.match(page, /closest\("\.app-content"\)\?\.scrollTo\(\{ top: 0 \}\)/);
  assert.match(css, /\.codex-config-fallback/);
  assert.match(css, /\.codex-ready-check/);
  assert.match(page, /no pegues el chat completo ni datos sensibles/i);
  assert.match(page, /Parte simple[\s\S]*Mejora en conjunto/);
  assert.match(page, /function ProjectSubmitPanel/);
  assert.match(page, /Enviar proyecto/);
  assert.match(page, /No publica, crea branch, sincroniza el chat ni cambia una pantalla automáticamente/i);
  assert.match(page, /Guardar borrador local/);
  assert.doesNotMatch(submitPanel, /data-event-id=/);
  assert.match(page, /Borrar este borrador local/);
  assert.match(page, /No se envió a una bandeja compartida/);
  assert.match(page, /maxLength=\{700\}/);
  assert.match(submitPanel, /localFeedbackIntake\.submit/);
  assert.doesNotMatch(submitPanel, /submitGeneralFeedback|fetch\(/);
  assert.match(localIntake, /remove\(id/);
  assert.doesNotMatch(page, /https:\/\/yol1-product-growth-lab\.vercel\.app\/api\/mcp/);
  assert.doesNotMatch(page, /Conectar mi[\s\S]*(?:ChatGPT|Claude)/);
  assert.doesNotMatch(page, /function BuilderWorkspace/);
  assert.match(knowledge, /piloto ya usa un servidor HTTPS/i);
  assert.match(knowledge, /GitHub versiona el código/i);
  assert.match(knowledge, /no copia la conversación completa/i);
  assert.match(css, /\.builder-copy-url[^}]*min-height:44px/i);
  assert.doesNotMatch(page, /hasMcpUrl|URL MCP remota por validar|URL MCP aún no habilitada|Mensaje disponible cuando exista conexión/);
  assert.match(page, /No pudimos copiar\. Selecciona el contenido correspondiente/);
  assert.match(page, /builder-copy-status[^>]*role="alert"/);
  assert.match(outputContract, /submission_mode[\s\S]*local_only/);
  assert.match(outputContract, /conversación completa de ChatGPT, Claude o Codex/i);
  assert.match(outputContract, /Borrar este borrador local/);
  assert.match(flowMap, /ninguna flecha representa sincronización de conversación, publicación o integración financiera real/i);
  assert.match(flowMap, /Revisión humana/);
  assert.match(builderPlan, /piloto público con herramientas de lectura y una escritura explícita/i);
  assert.match(builderPlan, /resumen estructurado que esa persona decide guardar explícitamente/i);
  assert.doesNotMatch(builderPlan, /contrato \*\*local y de solo lectura\*\*|No hay una URL pública aprobada por defecto/i);
  assert.match(nightBoard, /piloto MCP público con lectura y guardado explícito de un resumen estructurado/i);
  assert.doesNotMatch(nightBoard, /MCP sólo con compatibilidad\/URL validadas/i);
  assert.doesNotMatch(page, /teléfono es solo la vista de lo que el MCP vaya materializando/i);
});

test("el MCP público guarda sólo borradores explícitos, opacos y revisables", async () => {
  const route = await source("app/api/mcp/route.ts");
  const store = await source("lib/server/project-draft-store.ts");
  const projectApi = await source("app/api/projects/[id]/route.ts");
  const projectsApi = await source("app/api/projects/route.ts");
  const reviewApi = await source("app/api/review/route.ts");
  const review = await source("app/review/page.tsx");
  const projectReview = await source("app/review/project/[id]/page.tsx");
  assert.match(route, /export async function GET/);
  assert.match(route, /export async function POST/);
  assert.match(route, /public-pilot-explicit-write/);
  assert.match(route, /yol1_get_context/);
  assert.match(route, /yol1_start_builder/);
  assert.match(route, /yol1_create_project_brief/);
  assert.match(route, /yol1_save_project_draft/);
  assert.match(route, /yol1_get_project_draft/);
  assert.match(route, /yol1_get_lab_view/);
  assert.match(route, /tools\/list/);
  assert.match(route, /tools\/call/);
  assert.match(route, /SERVER_VERSION = "0\.8\.0"/);
  assert.match(route, /CONTEXT_VERSION = "yol1-lab-context\/0\.7"/);
  assert.match(route, /SCHEMA_VERSION = "project-draft\/0\.4"/);
  assert.match(route, /prototype_url/);
  assert.match(route, /rutas C:\\\\ o file:\/\//);
  assert.match(route, /url\.username \|\| url\.password/);
  assert.match(route, /url\.protocol !== "https:" \|\| isLocalPrototypeHost\(url\.hostname\)/);
  assert.match(route, /host === "localhost"/);
  assert.match(route, /workflow_mode: "legacy-compatible"/);
  assert.match(route, /loaded: \["product_context", "delivery_contract", "lab_view"\]/);
  assert.match(route, /Continúa aunque el cliente sólo muestre las herramientas originales/i);
  assert.match(route, /guía universalmente a personas con distintos niveles técnicos/i);
  assert.match(route, /design_system: designSystemManifest\(\)/);
  assert.match(route, /assistant_experience: assistantExperienceContract\(\)/);
  assert.match(route, /builder_guidance: builderGuidanceManifest\(\)/);
  assert.match(route, /artifact_experience: artifactExperienceManifest\(\)/);
  assert.match(route, /product_sheet: productSheetManifest\(\)/);
  assert.match(route, /technology_baseline: technologyBaselineManifest\(\)/);
  assert.match(route, /continuity: continuityManifest\(\)/);
  assert.match(route, /CONTEXT_MODULES = \["core", "product_sheet", "technology", "data_analytics", "continuity"\]/);
  assert.match(route, /context_modules_loaded: \["core", "product_sheet"\], delivery_guidance_loaded: true/);
  assert.doesNotMatch(route, /context_modules_loaded: \[[^\]]*"delivery"/);
  assert.match(route, /universal_for_every_collaborator_and_product_idea/);
  assert.match(route, /hide_until_proposal_exists: \["technical_sheet", "event_catalog", "architecture_details", "internal_tooling"\]/);
  assert.match(route, /only_skills_explicitly_exposed_and_relevant_to_the_current_task/);
  assert.match(route, /claim_the_mcp_can_enumerate_a_private_skill_catalog/);
  assert.match(route, /No abras con una ficha técnica/i);
  assert.match(route, /crea y abre en este mismo turno un único artefacto HTML interactivo/i);
  assert.match(route, /El artefacto vive en la cuenta y el chat de esa persona/i);
  assert.match(route, /Un disclaimer general al pie no corrige una afirmación engañosa/i);
  assert.match(route, /no introduzcas marcas de terceros dentro de la interfaz YOL1/i);
  assert.match(route, /acid: "#80ef0c"/);
  assert.match(route, /aqua: "#71d7c8"/);
  assert.match(route, /brand_night: "#112e3c"/);
  assert.match(route, /companion_navigation: \{\s*primary: \["Inicio", "Finanzas", "Ahorrar", "Deudas", "Mi banco"\],\s*secondary: \[\{ label: "Cartola", parent: "Finanzas" \}\],\s*screen_titles: \{ Deudas: "Tu plan de deuda" \},\s*\}/);
  assert.match(route, /controles de al menos 44 × 44 px/i);
  assert.match(route, /Nunca afirmes que una integración, pago, crédito, KYC, banco, licencia o partner está disponible sin evidencia explícita/i);
  assert.match(route, /No muestres trazas como “Now update…”/i);
  assert.match(route, /muestra una primera propuesta antes de preguntar/i);
  assert.match(route, /Esta es la entrada canónica[\s\S]*no llames además a create_project_brief/i);
  assert.match(route, /No preguntes el nivel técnico/i);
  assert.match(route, /Rescata conocimiento parcial/i);
  assert.match(route, /Amazon Cognito User Pools es candidato/i);
  assert.match(route, /DynamoDB y Aurora PostgreSQL permanecen alternativas futuras/i);
  assert.match(route, /Cruza la propuesta con Onboarding\/KYC, Acompañante financiero, Cuentas Claras, Home Banking, Tarjetas, Remesas pausado/i);
  assert.match(route, /alias_of: "yol1_start_builder"/);
  assert.match(route, /sólo después de una petición explícita/i);
  assert.match(route, /readOnlyHint: false, destructiveHint: false, idempotentHint: true/);
  assert.match(route, /No está publicado · No modificó ninguna pantalla automáticamente/);
  assert.match(route, /Verla en Reviews/);
  assert.match(route, /review_url: reviewUrl/);
  assert.match(route, /Alcanzaste el límite temporal de cinco borradores por hora/);
  assert.match(route, /datos personales, credenciales, teléfonos o números de tarjeta/);
  assert.match(route, /access_\?token\|api_\?key\|auth\|authorization\|code\|credential\|jwt\|password\|secret\|signature\|token/);
  assert.match(route, /url\.username \|\| url\.password/);
  assert.doesNotMatch(route, /DATABASE_URL|process\.env\.(?!NEXT_PUBLIC_(MCP_URL|SITE_URL))/);
  assert.match(store, /CREATE TABLE IF NOT EXISTS yol1_project_drafts/);
  assert.match(store, /ADD COLUMN IF NOT EXISTS product_sheet jsonb/);
  assert.match(store, /review_status text NOT NULL DEFAULT 'new'/);
  assert.match(store, /listProjectDrafts/);
  assert.match(store, /updateProjectDraftReview/);
  assert.match(store, /technology_fit: input\.productSheet\.technologyFit/);
  assert.match(store, /randomBytes\(16\)/);
  assert.match(store, /expires_at[\s\S]*90 days/);
  assert.match(store, /ON CONFLICT \(idempotency_hash\)/);
  assert.doesNotMatch(store, /email|phone|rut|conversation/i);
  assert.match(projectApi, /X-Robots-Tag/);
  assert.match(projectApi, /private, no-store/);
  assert.match(projectApi, /toPublicProjectDraft\(project\)/);
  assert.match(projectApi, /PublicProjectDraft/);
  assert.doesNotMatch(projectApi, /NextResponse\.json\(\{ project \}/);
  assert.match(projectsApi, /isReviewAuthorized/);
  assert.match(projectsApi, /export async function GET/);
  assert.match(projectsApi, /export async function PATCH/);
  assert.match(reviewApi, /Promise\.allSettled\(\[listFeedback\(\), listProjectDrafts\(\)\]\)/);
  assert.match(reviewApi, /isReviewAuthorized/);
  assert.match(review, /getReviewWorkspace/);
  assert.match(review, /status\.projects/);
  assert.match(review, /Abrimos el feedback, pero las propuestas compartidas no están disponibles/);
  assert.match(review, /Qué quiso construir/);
  assert.match(review, /Revisar propuesta/);
  assert.match(projectReview, /sandbox="allow-scripts"/);
  assert.match(projectReview, /referrerPolicy="no-referrer"/);
  assert.doesNotMatch(projectReview, /allow-popups|allow-modals|allow-forms/);
  const outputContract = await source("BUILDER-OUTPUT-CONTRACT.md");
  assert.match(outputContract, /project-draft\/0\.3/);
  assert.match(outputContract, /enlace opaco[\s\S]*nunca devuelve esos campos\s+editoriales/i);
  assert.match(outputContract, /`project_id`[\s\S]*`submission_id`[\s\S]*`value_proposition`[\s\S]*`expires_at`/);
  assert.match(outputContract, /`product_sheet`/);
  assert.doesNotMatch(outputContract, /`proposer_name`|`proposal_version`/);
});

test("bandeja de decisiones resuelve contradicciones solo en estado local", async () => {
  const review = await source("app/review/page.tsx");
  const decisions = await source("lib/decision-inbox.ts");
  assert.match(review, /02 · DECISIONES/i);
  assert.match(review, /A manda/);
  assert.match(review, /B manda/);
  assert.match(review, /Necesito más contexto/);
  assert.match(review, /Resolución archivada/);
  assert.match(review, /Ver archivadas/);
  assert.doesNotMatch(review, /FEEDBACK RELACIONADO/);
  assert.match(decisions, /localStorage/);
  assert.match(decisions, /Decisión verbal de Felipe/);
  assert.doesNotMatch(decisions, /fetch\(|github|OPENAI_API_KEY/i);
});

test("la referencia visual legada queda aislada del código ejecutable", async () => {
  const tsconfig = await source("tsconfig.json");
  assert.match(tsconfig, /design-system\/reference\/\*\*/);
});

test("las fichas semilla no inventan verificación ni estados de conocimiento", async () => {
  const productFiles = [
    "home-banking.md",
    "tarjetas.md",
    "remesas.md",
    "construir-mi-propio-producto.md",
  ];
  const allowedStates = new Set(["decidido", "candidato", "por_validar", "fuera_de_alcance"]);
  for (const file of productFiles) {
    const sheet = await source(`product-knowledge/products/${file}`);
    assert.match(sheet, /^knowledge_status: semilla$/m, file);
    assert.match(sheet, /^verified_through: null$/m, file);
    assert.match(sheet, /^source_export_id: null$/m, file);
    const coverageStart = sheet.indexOf("## Cobertura de frentes");
    const coverageEnd = sheet.indexOf("\n## ", coverageStart + 4);
    const coverage = sheet.slice(coverageStart, coverageEnd === -1 ? undefined : coverageEnd);
    const states = coverage.split("\n").filter((line) => line.startsWith("|") && !line.includes("|---") && !line.includes("| Frente ")).map((line) => line.split("|")[2]?.trim());
    assert.equal(states.length, 12, file);
    for (const state of states) assert.ok(allowedStates.has(state), `${file}: ${state}`);
  }
  const index = await source("product-knowledge/INDEX.md");
  assert.equal((index.match(/\| pendiente \|/g) || []).length, 4);
  assert.match(index, /snapshot local del 11 de agosto de 2026, fuera de esta carpeta/);
  assert.match(index, /disponible, pero todavía requiere confirmar alcance, registrar manifiesto y completar la reconciliación/);
  assert.doesNotMatch(index, /se espera el próximo paquete de Felipe/);
  const remittances = await source("product-knowledge/products/remesas.md");
  assert.match(remittances, /No se investiga, diseña ni prototipa en el ciclo vigente/);
});
