import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const source = (path) => readFile(new URL(path, root), "utf8");

test("Inicio conserva bandeja, acciones contextuales y elección IA/demo", async () => {
  const page = await source("app/page.tsx");
  assert.match(page, /Entiende tus finanzas/);
  assert.match(page, /Tienes \{visibleCards\.length/);
  assert.match(page, /Disney\+ aparece dos veces/);
  assert.match(page, /Tu tarjeta tiene restaurantes con descuento/);
  assert.match(page, /Le debes a Camila/);
  assert.match(page, /La cuenta de Liguria parece compartida/);
  assert.match(page, /Pregúntale a YOL1/);
  assert.match(page, /Usar IA/);
  assert.match(page, /Seguir en demo/);
  assert.match(page, /Ignorar/);
  assert.match(page, /Preparar reparto/);
  assert.match(page, /carousel-dots/);
  assert.match(page, /Deshacer última/);
  assert.match(page, /Se guarda para revisión por parte del equipo creador/i);
  assert.doesNotMatch(page, /Explorar ejemplo|Simular con mi información/);
  assert.doesNotMatch(page, /Micrófono de demo/);
});

test("la IA opera server-side con consentimiento, límites y fallback", async () => {
  const page = await source("app/page.tsx");
  const route = await source("app/api/chat/route.ts");
  const prompt = await source("lib/ai/yol1-prompt.ts");
  const knowledge = await source("lib/ai/knowledge.ts");
  const envExample = await source(".env.example");
  const evals = JSON.parse(await source("evals/yol1-cases.json"));
  assert.match(route, /process\.env\.OPENAI_API_KEY/);
  assert.match(route, /typedBody\.aiConsent !== true/);
  assert.match(route, /MAX_MESSAGES = 12/);
  assert.match(route, /MAX_MESSAGE_LENGTH = 700/);
  assert.match(route, /store: false/);
  assert.match(route, /api\.openai\.com\/v1\/responses/);
  assert.match(route, /createDemoResponse/);
  assert.doesNotMatch(page, /OPENAI_API_KEY|api\.openai\.com|Authorization:|Bearer /);
  assert.match(prompt, /No solicites claves/);
  assert.match(prompt, /Una coincidencia no es una conclusión/);
  assert.match(knowledge, /YOL1_KNOWLEDGE_VERSION/);
  assert.match(envExample, /OPENAI_API_KEY=\s*$/m);
  assert.doesNotMatch(envExample, /sk-[A-Za-z0-9]/);
  assert.ok(evals.length >= 4);
});

test("el conocimiento aprobado se resuelve antes de pedir IA", async () => {
  const route = await source("app/api/chat/route.ts");
  const catalog = await source("lib/ai/knowledge-catalog.ts");
  const router = await source("lib/ai/knowledge-router.ts");
  const viewer = await source("app/review/knowledge/page.tsx");
  const css = await source("app/globals.css");
  const index = await source("knowledge/INDEX.md");
  const workflow = await source("knowledge/WORKFLOW-POR-VOZ.md");
  assert.match(route, /routeKnowledge\(lastQuestion\)/);
  assert.ok(route.indexOf("localRoute.kind") < route.indexOf('fetch("https://api.openai.com/v1/responses"'), "el router local debe ejecutarse antes de la API");
  assert.match(router, /Qué veo:/);
  assert.match(router, /Qué significa:/);
  assert.match(router, /Qué puedes hacer ahora:/);
  assert.match(router, /No voy a inventar una respuesta/);
  assert.match(router, /calculateLabMonthResult/);
  assert.match(catalog, /lab-kb-2026-08-14\.1/);
  assert.match(index, /collect-receivables-001/);
  assert.match(workflow, /Felipe dicta/);
  assert.match(viewer, /Conocimiento del Lab/);
  assert.match(viewer, /Marcar para mejorar/);
  assert.match(viewer, /localStorage/);
  assert.doesNotMatch(viewer, /fetch\(|github|OPENAI_API_KEY/i);
  assert.match(css, /@media \(max-width:800px\)[\s\S]*\.knowledge-overview/);
  assert.match(css, /\.knowledge-answer,\.knowledge-columns \{ grid-template-columns:1fr/);
});

test("feedback y respuestas llegan a una bandeja editorial con fallback local", async () => {
  const page = await source("app/page.tsx");
  const review = await source("app/review/page.tsx");
  const readme = await source("README.md");
  const adapter = await source("lib/learning-review.ts");
  const sharedClient = await source("lib/shared-feedback-client.ts");
  const architecture = await source("AI-ARCHITECTURE.md");
  assert.match(page, /Útil/);
  assert.match(page, /Mejoraría/);
  assert.match(page, /localChatFeedbackIntake\.submit/);
  assert.match(page, /submitChatResponse/);
  assert.match(review, /Bandeja de aprendizaje/);
  assert.match(review, /Feedback que dejó la gente/);
  assert.match(review, /En revisión/);
  assert.match(review, /Para después/);
  assert.match(review, /Resuelto/);
  assert.match(review, /Marcar resuelto/);
  assert.doesNotMatch(review, /Convertido en mejora, guía o proyecto/);
  assert.match(readme, /Para después, Resuelto o Ignorado/);
  assert.doesNotMatch(readme, /Para después, Convertido o Ignorado/);
  assert.match(review, /Hallazgos para interpretar/);
  assert.match(review, /¿Qué debe cambiar\?/);
  assert.match(review, /window\.localStorage\.setItem\("yol1-lab-theme", next\)/);
  assert.match(review, /button onClick=\{chooseTheme\}/);
  assert.match(adapter, /localStorage/);
  assert.doesNotMatch(adapter, /fetch\(|github\.com|api\.github/i);
  assert.match(sharedClient, /fetch\("\/api\/feedback"/);
  assert.doesNotMatch(sharedClient, /DATABASE_URL|YOL1_REVIEW_TOKEN/);
  assert.match(architecture, /nunca reescribe automáticamente/i);
});

test("brief y ciclo QA conservan estados editoriales y alcance canónicos", async () => {
  const brief = await source("BRIEF-NOCHE-EJECUCION.md");
  const qaCycle = await source("QA-CICLO-TRIPLE.md");
  const productDesign = await source("PRODUCT-DESIGN.md");
  const onboardingPrd = await source("PRD-ONBOARDING-KYC-PROGRESIVO.md");
  const technicalStandard = await source("ESTANDAR-QA-TECNICO-PRD.md");
  const nightBoard = await source("TABLERO-NOCHE.md");
  const nightPlan = await source("PLAN-NOCHE-YOL1.md");
  const onboardingScope = brief.match(/## 3\. Onboarding y KYC progresivo[\s\S]*?(?=\n## 4\.)/)?.[0] ?? "";
  const remittancesScope = brief.match(/## 6\. Remesas[\s\S]*?(?=\n## 7\.)/)?.[0] ?? "";
  const confirmedDirection = brief.match(/## 10\. Dirección de producto confirmada por Felipe[\s\S]*?(?=\n## 11\.)/)?.[0] ?? "";
  const synthesis = brief.match(/## 11\. Síntesis de las tres auditorías[\s\S]*?(?=\n## 12\.)/)?.[0] ?? "";
  const priorities = qaCycle.match(/## Prioridades actuales[\s\S]*$/)?.[0] ?? "";
  const remittancesPlan = nightPlan.match(/### Remesas[\s\S]*?(?=\n### Construir mi propio producto)/)?.[0] ?? "";
  assert.match(onboardingScope, /acceso gradual gobernado por una capacidad aprobada/);
  assert.doesNotMatch(onboardingScope, /desbloqueo incremental según KYC, licencias y producto/);
  assert.match(remittancesScope, /Fuera de alcance hasta nueva instrucción de Felipe/);
  assert.match(remittancesScope, /No investigar, definir, diseñar ni prototipar/);
  assert.doesNotMatch(remittancesScope, /Solo investigación y definición/);
  assert.match(confirmedDirection, /KYC puede ser un requisito progresivo de una capacidad aprobada, pero nunca la habilita por sí solo/);
  assert.doesNotMatch(confirmedDirection, /KYC es una progresión que desbloquea capacidades/);
  assert.match(synthesis, /Nuevo, En revisión, Guardar para después, Resuelto e Ignorado/);
  assert.doesNotMatch(synthesis, /Guardar para después, Convertido e Ignorado/);
  assert.match(synthesis, /destino `mejora \/ guía Markdown \/ proyecto` sigue siendo una decisión aparte/);
  assert.match(priorities, /Remesas queda fuera de alcance hasta nueva instrucción/);
  assert.doesNotMatch(priorities, /Remesas queda en investigación/);
  assert.match(qaCycle, /Por cada pantalla implementada o propuesta que pase a revisión/);
  assert.match(qaCycle, /actualización de la especificación interna, PRD/);
  assert.doesNotMatch(qaCycle, /Por cada pantalla publicada|actualización de Ficha de producto/);
  assert.match(technicalStandard, /especificación interna de producto del Lab/);
  assert.match(technicalStandard, /no la renderiza en la experiencia pública/);
  assert.doesNotMatch(technicalStandard, /Aplica a los productos publicados|El Lab ya expone una Ficha por pantalla/);
  assert.match(productDesign, /no se agregan diagonales ni triángulos decorativos al pie/);
  assert.match(productDesign, /Las fichas de producto[\s\S]*son material interno y no se renderizan en la experiencia pública/);
  assert.match(productDesign, /Feedback permanece disponible en todos los espacios/);
  assert.match(onboardingPrd, /La especificación interna resume la regla crítica/);
  assert.doesNotMatch(onboardingPrd, /La ficha pública resume la regla crítica/);
  assert.doesNotMatch(productDesign, /Acid identifica el único producto publicado/);
  assert.doesNotMatch(productDesign, /La Ficha de producto vive debajo del teléfono/);
  assert.match(nightBoard, /borrador local en investigación/);
  assert.doesNotMatch(nightBoard, /borrador local no publicado/);
  assert.match(remittancesPlan, /Fuera de alcance: no abrir preguntas, research, diseño ni prototipos/);
  assert.doesNotMatch(remittancesPlan, /¿Quién envía|¿Qué dolor|¿Qué debe poder entender|¿Qué partner/);
  assert.doesNotMatch(nightPlan, /pantallas actuales, tanto local como la versión publicada/);
});

test("el registro nocturno conserva secciones consecutivas en orden", async () => {
  const brief = await source("BRIEF-NOCHE-EJECUCION.md");
  const sections = [...brief.matchAll(/^## (\d+)\./gm)].map((match) => Number(match[1]));
  assert.deepEqual(sections, Array.from({ length: sections.length }, (_, index) => index + 1));
});

test("intake compartido protege Postgres y la revisión privada", async () => {
  const route = await source("app/api/feedback/route.ts");
  const store = await source("lib/server/feedback-store.ts");
  const page = await source("app/page.tsx");
  const envExample = await source(".env.example");
  assert.match(route, /YOL1_REVIEW_TOKEN/);
  assert.match(route, /timingSafeEqual/);
  assert.match(route, /sameOrigin/);
  assert.match(route, /containsSensitiveData/);
  assert.match(route, /countRecentFeedback\(sessionHash\) >= 20/);
  assert.match(route, /status === "wrong" && !reviewNote/);
  assert.match(store, /process\.env\.DATABASE_URL/);
  assert.match(store, /CREATE TABLE IF NOT EXISTS yol1_feedback_items/);
  assert.match(store, /ON CONFLICT \(id\) DO UPDATE/);
  assert.match(store, /session_hash/);
  assert.doesNotMatch(page, /DATABASE_URL|YOL1_REVIEW_TOKEN|@neondatabase/);
  assert.match(envExample, /DATABASE_URL=\s*$/m);
  assert.match(envExample, /YOL1_REVIEW_TOKEN=\s*$/m);
  assert.doesNotMatch(envExample, /postgres(?:ql)?:\/\/[^\s]+:[^\s]+@/i);
});

test("acciones y confirmaciones permanecen simuladas y visibles", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  assert.match(page, /phone-toast/);
  assert.match(css, /\.phone-toast/);
  assert.match(page, /No cobra, paga ni contacta a nadie/i);
  assert.match(page, /no se conecta ninguna cuenta/i);
  assert.match(page, /no se carga ningún archivo/i);
  assert.match(page, /no conecta bancos y no envía nada por WhatsApp/i);
  assert.match(page, /no se inició un pago real/i);
  assert.doesNotMatch(page, /pago exitoso|dinero transferido|banco conectado/i);
});

test("Cartola usa navegación general e individual y acciones coherentes", async () => {
  const page = await source("app/page.tsx");
  assert.match(page, /Ver cartola general/);
  assert.match(page, /\["General", "BCI", "MACH"\]/);
  assert.match(page, /"Marcar revisado" \| "Revisar" \| "Preparar reparto" \| "Preparar cobro"/);
  assert.match(page, /ASISTENTE DEMO/);
  assert.match(page, /Guardar nota del ejemplo/);
  assert.match(page, /Nota guardada/);
  assert.match(page, /Revisado/);
  assert.match(page, /movement-detail-meta/);
  assert.doesNotMatch(page, /\{movement\.bank\} · \{movement\.code\}/);
});

test("Cobrar y pagar cubre ambos lados y conserva borrador en la app", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  assert.match(page, /Cobrar y pagar/);
  assert.match(page, /ME DEBEN/);
  assert.match(page, /LE DEBO/);
  assert.match(page, /Por persona/);
  assert.match(page, /Por grupo \/ gasto/);
  assert.match(page, /collectDraft/);
  assert.match(page, /Crear contacto demo/);
  assert.match(page, /@josefa/);
  assert.match(page, /Marcar como resuelto/);
  assert.match(page, /Preparar cobro/);
  assert.match(page, /Preparar pago/);
  assert.match(page, /Revisar si este pago ya quedó resuelto/);
  assert.match(page, /Nuevo gasto compartido/);
  assert.match(page, /Agregar deuda pendiente/);
  assert.match(page, /Repartir lo que falta/);
  assert.match(page, /collect-home-mode/);
  assert.match(css, /\.pending-board[^}]*grid-template-rows:minmax\(0,1fr\) minmax\(0,1fr\)/i);
  assert.match(css, /\.pending-lane-track[^}]*overflow-y:auto/i);
  assert.match(css, /\.pending-lane-track[^}]*overflow-x:hidden/i);
  assert.match(css, /\.app-content\.collect-home-mode[^}]*overflow:hidden/i);
  assert.match(css, /overscroll-behavior:contain/i);
  assert.match(page, /VISTA PREVIA DE MENSAJE/);
  assert.match(page, /Sigues dentro de YOL1/);
  assert.match(page, /Volver a YOL1/);
  assert.match(page, /Ver texto de ejemplo/);
  assert.match(page, /https:\/\/paga\.yol1\.example\/s\/demo-2841/);
  assert.match(page, /consentimiento explícito, un link generado en servidor y un partner de pagos autorizado/i);
  assert.match(page, /setMessagePreview\(null\)/);
  assert.doesNotMatch(page, /href=.*paga\.yol1\.example|window\.open|wa\.me|api\.whatsapp/i);
  assert.doesNotMatch(page, /Simular copia/);
});

test("lenguaje cotidiano, navegación literal y estados de confianza quedan visibles", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  assert.match(page, /Te entró/);
  assert.match(page, /Gastaste/);
  assert.match(page, /💵/);
  assert.match(page, /👥/);
  assert.match(page, /🪙/);
  assert.match(page, /Gana más lucas/);
  assert.match(page, /Mi banco/);
  assert.match(page, /Feedback/);
  assert.match(page, /Claro/);
  assert.match(page, /Oscuro/);
  assert.match(css, /\.bottom-nav button>small[^}]*font-size:9px/i);
});

test("Ahorrar ordena la conclusión antes de la evidencia sin ocultar transparencia", async () => {
  const page = await source("app/page.tsx");
  assert.match(page, /Ver por qué/);
  assert.match(page, /Ignorar/);
  assert.match(page, /Recuperar última/);
  assert.match(page, /Puede convenirte/);
  assert.match(page, /Evidencia/);
  assert.match(page, /Certeza/);
  assert.match(page, /Disclosure/);
});

test("tema dual y acentos semánticos están tokenizados", async () => {
  const css = await source("app/globals.css");
  const design = await source("PRODUCT-DESIGN.md");
  assert.match(css, /\.lab-shell\[data-theme="dark"\]/);
  assert.match(css, /\.lab-shell\[data-theme="light"\]/);
  assert.match(css, /--neon-pink:#ff8fb4/i);
  assert.match(css, /--violet-soft:/i);
  assert.match(css, /\.collect-hero[^}]*box-shadow:[^}]*var\(--neon-pink\)/i);
  assert.match(css, /\.pending-actions button:nth-child\(2\)[^}]*background:var\(--neon-pink\)/i);
  assert.match(css, /\.movement\.selected[^}]*var\(--aqua\)/i);
  assert.match(design, /nunca error, alerta ni dato crítico/i);
});

test("documenta límites y gates de aprendizaje", async () => {
  const spec = await source("MVP-SPEC.md");
  assert.match(spec, /E2 — Comprensión/);
  assert.match(spec, /E3 — Acción voluntaria/);
  assert.match(spec, /E4 — Resultado \/ retorno/);
  assert.match(spec, /No demuestra demanda, product-market fit, economics ni readiness/i);
  assert.match(spec, /Directo y Embebido quedan fuera/i);
});

test("feedback conserva fallback local y permanece desacoplado de GitHub", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  const adapter = await source("lib/feedback-intake.ts");
  const architecture = await source("FEEDBACK-INTAKE.md");
  assert.match(page, /product=\{activeProduct\.name\} screen=\{activeTitle\} open=\{true\}/);
  assert.match(page, /key=\{`desktop-feedback-\$\{productId\}-\$\{activeTitle\}`\}/);
  assert.match(page, /key=\{`mobile-feedback-\$\{productId\}-\$\{activeTitle\}`\}/);
  assert.match(page, /variant="desktop" compact=\{false\}/);
  assert.match(page, /Me gusta/);
  assert.match(page, /Mejoraría/);
  assert.match(page, /Idea/);
  assert.match(page, /No incluyas datos financieros ni personales/);
  assert.doesNotMatch(page, /life-shot|yol1-life\.jpg/);
  assert.match(css, /\.feedback-desktop[^}]*position:static/i);
  assert.doesNotMatch(css, /\.feedback-desktop[^}]*position:absolute/i);
  assert.doesNotMatch(page, /className="module-map"/);
  assert.match(css, /@media \(max-width:720px\)[\s\S]*\.feedback-mobile\.feedback-open/i);
  assert.match(css, /inset:62px 8px 70px/i);
  assert.match(adapter, /localStorage/);
  assert.match(adapter, /FeedbackIntakeAdapter/);
  assert.doesNotMatch(adapter, /github\.com|api\.github|Authorization|Bearer/i);
  assert.match(architecture, /ruta server-side protegida|POST \/api\/feedback/i);
  assert.match(architecture, /branch \+ PR.*aprobación|branch\/PR.*aprobación/i);
});

test("portfolio mantiene seis productos y tres prototipos explorables", async () => {
  const page = await source("app/page.tsx");
  const portfolio = await source("lib/product-portfolio.ts");
  const css = await source("app/globals.css");
  const definitions = portfolio.match(/\{ id: "(?:companion|kyc|banking|cards|remittances|builder)"/g) ?? [];
  assert.equal(definitions.length, 6);
  assert.match(portfolio, /name: "Acompañante financiero"[\s\S]*explorable: true/);
  assert.match(portfolio, /name: "Onboarding y KYC progresivo"/);
  assert.match(portfolio, /name: "Home Banking"/);
  assert.match(portfolio, /name: "Tarjetas"/);
  assert.match(portfolio, /name: "Remesas"/);
  assert.match(portfolio, /name: "Construir mi propio producto"/);
  assert.equal((portfolio.match(/explorable: true/g) ?? []).length, 3);
  assert.equal((portfolio.match(/explorable: false/g) ?? []).length, 3);
  assert.doesNotMatch(portfolio, /published: (?:true|false)/);
  assert.doesNotMatch(portfolio, /flujo publicado|Especificaciones de producto publicadas/);
  assert.doesNotMatch(css, /productos publicados|experiencias publicadas/);
  assert.match(page, /EN INVESTIGACIÓN/);
  assert.doesNotMatch(page, /Volver al Acompañante financiero/);
  assert.match(portfolio, /EMPTY_STATE_LIBRARY[\s\S]*perro feliz que te hará compañía/i);
  assert.match(portfolio, /acá hay un gato tecleando/i);
  assert.match(portfolio, /Alguien no hizo la pega/i);
  assert.match(portfolio, /Remesas no está siendo trabajada ahora/i);
  assert.match(portfolio, /ChatGPT o Claude/);
  assert.match(portfolio, /Un robot está ordenando los post-its/i);
  assert.ok((portfolio.match(/gesture: "/g) ?? []).length >= 12);
  assert.doesNotMatch(portfolio, /eyebrow: "NO PUBLICADO"/);
  assert.match(css, /@keyframes dog-tail-wag/);
  assert.match(css, /@keyframes cat-type/);
  assert.match(css, /@keyframes robot-note-shuffle/);
  assert.doesNotMatch(page, /MCP conectado|banco conectado|KYC aprobado|remesa enviada/i);
});

test("los contratos de producto siguen internos y no se montan en la experiencia pública", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  const portfolio = await source("lib/product-portfolio.ts");
  const feedback = await source("lib/feedback-intake.ts");
  assert.match(page, /ProductSpecPanel/);
  assert.match(page, /FICHA DE PRODUCTO · PARA DESARROLLO/);
  assert.doesNotMatch(page, /activeProduct\.explorable && <ProductSpecPanel/);
  assert.match(css, /\.team-spec \{ grid-column:1\/-1; width:100%/);
  assert.doesNotMatch(page, /Felipe resuelve contradicciones|Estado de revisión/);
  assert.match(page, /onFocusCapture/);
  assert.match(page, /control\.closest\("\.phone"\)/);
  assert.match(page, /phone_control_interacted/);
  assert.match(page, /phone_field_interacted/);
  assert.match(page, /data-instrumentation-ignore="true"/);
  assert.match(page, /data-event-id="companion_navigation_selected"/);
  assert.match(page, /data-event-id="profile_menu_opened"/);
  assert.match(page, /data-event-id="theme_mode_toggled"/);
  assert.match(portfolio, /eventMetadata\(/);
  assert.match(portfolio, /user_id/);
  assert.match(portfolio, /event_at/);
  assert.match(portfolio, /product_key/);
  assert.match(portfolio, /screen_key/);
  assert.match(portfolio, /action_key/);
  assert.match(portfolio, /simpleEventName\(/);
  assert.match(portfolio, /data:\s*\{ store:/);
  assert.match(portfolio, /questions:/);
  assert.match(portfolio, /risks:/);
  assert.match(portfolio, /React Native/);
  assert.match(portfolio, /AWS/);
  assert.match(portfolio, /"No aplica" \| "Por validar" \| "Requerido"/);
  assert.match(portfolio, /Chile es la jurisdicción base/);
  assert.match(feedback, /product\?: string/);
  assert.doesNotMatch(page, /analytics\.track|gtag\(|mixpanel|segment\.track/i);
});

test("los productos en investigación no simulan una app ni muestran ficha técnica", async () => {
  const page = await source("app/page.tsx");
  const css = await source("app/globals.css");
  assert.match(page, /productId === "companion" \|\| productId === "kyc"/);
  assert.doesNotMatch(page, /productId === "cards" && <CardsDiscovery/);
  assert.match(page, /TENGO UNA IDEA/);
  assert.doesNotMatch(page, /ProductSpecification|living-spec/);
  assert.match(page, /className="research-phone"/);
  assert.match(page, /className="research-halo"/);
  assert.match(css, /\.research-phone \{/);
  assert.match(css, /\.research-halo \{/);
  assert.doesNotMatch(page, /Unpublished|unpublished/);
  assert.doesNotMatch(css, /unpublished/);
});

test("el builder separa la conversación externa de la vista previa y el envío editorial", async () => {
  const page = await source("app/page.tsx");
  const knowledge = await source("knowledge/construir-mi-propio-producto.md");
  const css = await source("app/globals.css");
  const outputContract = await source("BUILDER-OUTPUT-CONTRACT.md");
  const flowMap = await source("BUILDER-FLOW-MAP.md");
  const localIntake = await source("lib/feedback-intake.ts");
  const submitPanel = page.slice(page.indexOf("function ProjectSubmitPanel"), page.indexOf("function ResearchStage"));
  assert.match(page, /function ProjectBuilderScreen/);
  assert.match(page, /En este espacio,[\s\S]*el próximo producto lo construyes tú/);
  assert.match(page, /YOL1 no lee ni sincroniza tu conversación/i);
  assert.match(page, /Ver guía para[\s\S]*ChatGPT/);
  assert.match(page, /Ver guía para[\s\S]*Claude/);
  assert.match(page, /Cómo ocupar/);
  assert.match(page, /NEXT_PUBLIC_MCP_URL/);
  assert.match(page, /Abrir la vista del Lab ahora/);
  assert.match(page, /No debes editar ningún prompt/i);
  assert.match(page, /Con <b>@YOL1<\/b> seleccionado, escribe <b>“Partamos.”<\/b>/i);
  assert.match(page, /YOL1 se encarga de darte la bienvenida/i);
  assert.match(page, /Copiado manualmente · no sincronizado/i);
  assert.match(page, /data-event-id="builder_guide_viewed" data-client="chatgpt"/);
  assert.match(page, /data-event-id="builder_guide_viewed" data-client="claude"/);
  assert.match(page, /no pegues el chat completo ni datos sensibles/i);
  assert.match(page, /Hablas[\s\S]*Lo conviertes en propuesta/);
  assert.match(page, /function ProjectSubmitPanel/);
  assert.match(page, /Enviar proyecto/);
  assert.match(page, /No publica, crea branch, sincroniza el chat ni cambia una pantalla automáticamente/i);
  assert.match(page, /Guardar borrador local/);
  assert.doesNotMatch(submitPanel, /data-event-id=/);
  assert.match(page, /Borrar este borrador local/);
  assert.match(page, /No se envió a una bandeja compartida/);
  assert.match(page, /maxLength=\{700\}/);
  assert.match(submitPanel, /localFeedbackIntake\.submit/);
  assert.doesNotMatch(submitPanel, /submitGeneralFeedback|fetch\(/);
  assert.match(localIntake, /remove\(id/);
  assert.doesNotMatch(page, /https:\/\/yol1-product-growth-lab\.vercel\.app\/api\/mcp/);
  assert.doesNotMatch(page, /Conectar mi[\s\S]*(?:ChatGPT|Claude)/);
  assert.doesNotMatch(page, /function BuilderWorkspace/);
  assert.match(knowledge, /servidor HTTPS desplegado, OAuth/i);
  assert.match(knowledge, /GitHub versiona el código/i);
  assert.match(knowledge, /El MCP de lectura no materializa pantallas ni sincroniza la conversación/i);
  assert.match(css, /\.builder-copy-url:disabled[^}]*cursor:not-allowed/i);
  assert.match(css, /\.builder-copy-url[^}]*min-height:44px/i);
  assert.match(page, /No pudimos copiar la URL/);
  assert.match(page, /builder-copy-status[^>]*role="alert"/);
  assert.match(outputContract, /submission_mode[\s\S]*local_only/);
  assert.match(outputContract, /conversación completa de ChatGPT o Claude/i);
  assert.match(outputContract, /Borrar este borrador local/);
  assert.match(flowMap, /ninguna flecha representa sincronización, publicación o integración real/i);
  assert.match(flowMap, /Revisión humana/);
  assert.doesNotMatch(page, /teléfono es solo la vista de lo que el MCP vaya materializando/i);
});

test("el MCP local expone solo contexto y briefs sin prometer disponibilidad externa", async () => {
  const route = await source("app/api/mcp/route.ts");
  assert.match(route, /export async function GET/);
  assert.match(route, /export async function POST/);
  assert.match(route, /local-read-only-demo/);
  assert.match(route, /yol1_get_context/);
  assert.match(route, /yol1_start_builder/);
  assert.match(route, /yol1_create_project_brief/);
  assert.match(route, /yol1_get_lab_view/);
  assert.match(route, /tools\/list/);
  assert.match(route, /tools\/call/);
  assert.match(route, /No implica endpoint público, compatibilidad de cliente ni autorización operativa/);
  assert.doesNotMatch(route, /DATABASE_URL|process\.env\.(?!NEXT_PUBLIC_(MCP_URL|SITE_URL))/);
});

test("bandeja de decisiones resuelve contradicciones solo en estado local", async () => {
  const review = await source("app/review/page.tsx");
  const decisions = await source("lib/decision-inbox.ts");
  assert.match(review, /02 · DECISIONES/i);
  assert.match(review, /A manda/);
  assert.match(review, /B manda/);
  assert.match(review, /Necesito más contexto/);
  assert.match(review, /Felipe manda · resolución local visible/);
  assert.doesNotMatch(review, /FEEDBACK RELACIONADO/);
  assert.match(decisions, /localStorage/);
  assert.match(decisions, /Decisión verbal de Felipe/);
  assert.doesNotMatch(decisions, /fetch\(|github|OPENAI_API_KEY/i);
});
