"use client";

import { useState } from "react";
import { buildDebtHealthSummary, DEBT_HEALTH_DEMO, transitionPlanItem, type DebtHealthStage, type PlanItemState } from "../lib/debt-health-demo";

const money = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });

export function DebtHealthDemo({ onLedger, onNotice }: { onLedger: (filter?: string, selected?: string) => void; onNotice: (message: string) => void }) {
  const [stage, setStage] = useState<DebtHealthStage>("summary");
  const [planState, setPlanState] = useState<PlanItemState>("pending");
  const summary = buildDebtHealthSummary(DEBT_HEALTH_DEMO);
  const obligation = DEBT_HEALTH_DEMO.obligations[0];
  const evidence = DEBT_HEALTH_DEMO.evidence;

  if (stage === "evidence") return <section className="debt-health"><button className="back-link" onClick={() => setStage("summary")}>← Volver a mi situación</button><p className="kicker">PAGO POR CONFIRMAR · EJEMPLO</p><h2 className="compact-title">Las fechas no cuentan<br /><span>la misma historia.</span></h2><p className="debt-health-lead">Una coincidencia ayuda a investigar; no confirma que el pago haya sido aplicado.</p><div className="debt-evidence-compare"><article><small>QUÉ VIMOS</small><strong>{evidence.sourceLabel} · 22 ago</strong><b>{money.format(evidence.amount)}</b><p>Pago observado en un movimiento sintético.</p></article><article><small>QUÉ MUESTRA EL INFORME</small><strong>Informe demo · 19 ago</strong><b>{money.format(obligation.reportedBalance)}</b><p>Todavía muestra el saldo anterior.</p></article></div><div className="debt-health-boundary"><strong>Qué significa</strong><p>Puede ser un desfase de actualización. No concluimos error, mora ni pago confirmado.</p></div><button className="primary-action" onClick={() => setStage("plan")}>Ver el primer paso →</button><button className="secondary-action" onClick={() => onLedger("General", "formal-payment-demo")}>Ver movimiento demo</button></section>;

  if (stage === "plan") return <section className="debt-health"><button className="back-link" onClick={() => setStage("evidence")}>← Volver a la evidencia</button><p className="kicker">TU PRIMER PASO · EJEMPLO</p><h2 className="compact-title">Confirma antes<br /><span>de decidir qué hacer.</span></h2><p className="debt-health-lead">Todavía no sabemos si el pago está mal aplicado. Busca evidencia nueva antes de sacar una conclusión.</p><div className="debt-plan-list" aria-live="polite"><article className="primary-plan"><span>01</span><div><strong>Revisar si el pago fue aplicado</strong><p>Evidencia esperada: saldo actualizado o estado de cuenta.</p><small>{planState === "pending" ? "PENDIENTE" : planState === "user_marked" ? "TÚ LO MARCASTE · FALTA EVIDENCIA" : planState === "confirmed" ? "CONFIRMADO CON EVIDENCIA" : "REABIERTO"}</small></div></article><article><span>02</span><div><strong>Mirar el próximo vencimiento</strong><p>5 sep · fecha respaldada por este fixture.</p></div></article><article><span>03</span><div><strong>Completar costos que faltan</strong><p>CAE, costo total y seguros antes de comparar alternativas.</p><small>DESPUÉS</small></div></article></div>{planState === "pending" || planState === "reopened" ? <button className="primary-action" onClick={() => { setPlanState((state) => transitionPlanItem(state, "mark")); onNotice("Paso marcado por ti. Todavía falta evidencia para confirmarlo."); }}>Marcar para confirmar</button> : <button className="secondary-action" onClick={() => setPlanState((state) => transitionPlanItem(state, "reopen"))}>Deshacer marca</button>}<p className="debt-health-disclaimer">Cuando tengas nueva evidencia, vuelve y actualizamos la lectura. Esto no es un score ni una recomendación de crédito.</p></section>;

  return <section className="debt-health"><p className="kicker">TU DEUDA · EJEMPLO</p><h2 className="compact-title">Primero entendamos<br /><span>qué está pasando.</span></h2><p className="debt-health-lead">No vemos mora activa con estos datos. Sí hay un pago por confirmar y costos que todavía faltan.</p><div className="debt-health-grid"><article><small>INVENTARIO</small><strong>{summary.obligationCount} obligaciones</strong><p>{money.format(summary.reportedBalance)} reportados · corte 19 ago</p></article><article><small>URGENCIA</small><strong>{summary.lateCount} en mora</strong><p>1 pago por confirmar</p></article><article><small>PRESIÓN CONOCIDA</small><strong>{money.format(summary.knownMonthlyPressure)}</strong><p>Cuotas conocidas · cobertura parcial</p></article></div><div className="debt-health-boundary"><strong>Lo que todavía no sabemos</strong><p>Faltan costos y una cuota. Por eso no clasificamos esta deuda como “manejable” ni recomendamos refinanciar.</p></div><button className="primary-action" onClick={() => setStage("evidence")}>Ver el primer paso →</button><p className="debt-health-disclaimer">Fixture local · no conecta bancos, CMF ni Floid. No es un score.</p></section>;
}
