import { PaymentProviderError } from "./payment-provider.ts";

const STATUS_BY_CODE: Record<string, number> = {
  GROUP_NOT_FOUND: 404,
  EXPENSE_NOT_FOUND: 404,
  DEBT_NOT_FOUND: 404,
  PAYMENT_ATTEMPT_NOT_FOUND: 404,
  INVALID_EXPENSE: 422,
  EXPENSE_AMOUNT_EXCEEDS_LIMIT: 422,
  INVALID_EXPENSE_COMMAND_ID: 400,
  INVALID_EXPENSE_CORRECTION_COMMAND_ID: 400,
  INVALID_EXPENSE_CORRECTION_REASON: 422,
  INVALID_EXPENSE_CORRECTION_SOURCE: 409,
  EXPENSE_CORRECTION_ALREADY_REPLACED: 409,
  EXPENSE_CORRECTION_GROUP_CHANGED: 409,
  EXPENSE_CORRECTION_NOT_OWNED: 403,
  EXPENSE_ALREADY_CANCELLED_FOR_CORRECTION: 409,
  EXPENSE_CORRECTION_PAYMENT_IN_PROGRESS: 409,
  EXPENSE_CORRECTION_HAS_PAYMENT: 409,
  EXPENSE_CORRECTION_RECURRING_ACTIVE: 409,
  INVALID_GROUP_COMMAND_ID: 400,
  INVALID_CLP_AMOUNT: 422,
  DUPLICATE_PARTICIPANT: 422,
  INVALID_SIMULATION_STATUS: 400,
  INVALID_EXPENSE_TITLE: 422,
  INVALID_PAYMENT_AMOUNT: 422,
  PAYMENT_EXCEEDS_OUTSTANDING: 409,
  ACTIVE_PAYMENT_ATTEMPT_EXISTS: 409,
  DEBT_NOT_PAYABLE: 409,
  SPLIT_DOES_NOT_MATCH_TOTAL: 422,
  INVALID_SPLIT_MODE: 422,
  INVALID_SPLIT_VALUES: 422,
  SPLIT_VALUES_REQUIRED: 422,
  SPLIT_VALUES_NOT_ALLOWED: 422,
  SPLIT_VALUE_KEYS_MISMATCH: 422,
  INVALID_SPLIT_WEIGHT: 422,
  INVALID_PERCENTAGE_BPS: 422,
  PERCENTAGE_TOTAL_MUST_BE_10000: 422,
  INVALID_SHARE_WEIGHT: 422,
  SHARE_WEIGHT_LIMIT_EXCEEDED: 422,
  PARTICIPANT_NOT_IN_GROUP: 422,
  PAYER_MUST_PARTICIPATE: 422,
  INVALID_GROUP_NAME: 422,
  GROUP_NEEDS_PARTICIPANTS: 422,
  PARTICIPANT_NOT_FOUND: 404,
  SETTLED_PAYMENT_IS_FINAL: 409,
  STALE_PAYMENT_ATTEMPT: 409,
  CONCURRENT_STATE_UPDATE: 409,
  IDEMPOTENCY_CONFLICT: 409,
  PAYMENT_CREATION_IN_PROGRESS: 409,
  INVALID_PAYMENT_STATUS_TRANSITION: 409,
  TOO_MANY_PARTICIPANTS: 422,
  INVALID_IDEMPOTENCY_KEY: 400,
  INVALID_RECURRENCE_COMMAND_ID: 400,
  INVALID_RECURRENCE_DATE: 422,
  RECURRING_TEMPLATE_NOT_FOUND: 404,
  EXPENSE_ALREADY_RECURRING: 409,
  RECURRING_TEMPLATE_NOT_ACTIVE: 409,
  RECURRENCE_OCCURRENCE_STALE: 409,
  RECURRENCE_OCCURRENCE_SKIPPED: 409,
  RECURRENCE_OCCURRENCE_ALREADY_MATERIALIZED: 409,
  RECURRENCE_TEMPLATE_STALE: 409,
  RECURRING_TEMPLATE_LIMIT_REACHED: 422,
  RECURRENCE_OCCURRENCE_LIMIT_REACHED: 422,
  INVALID_COLLECTION_COMMAND_ID: 400,
  INVALID_COLLECTION_MESSAGE_KIND: 422,
  COLLECTION_NOT_OWNED: 403,
  DEBT_NOT_COLLECTABLE: 409,
  COLLECTION_FOLLOW_UP_REQUIRES_INITIAL: 409,
  COLLECTION_CONFIRMATION_LIMIT_REACHED: 422,
  INVALID_RECONCILIATION_COMMAND_ID: 400,
  INVALID_RECONCILIATION_FIXTURE: 400,
  RECONCILIATION_CANDIDATE_NOT_FOUND: 404,
  RECONCILIATION_ENTRY_NOT_FOUND: 404,
  RECONCILIATION_DECISION_NOT_FOUND: 404,
  RECONCILIATION_NOT_OWNED: 403,
  RECONCILIATION_CANDIDATE_STALE: 409,
  RECONCILIATION_ENTRY_ALREADY_USED: 409,
  RECONCILIATION_PAYMENT_IN_PROGRESS: 409,
  RECONCILIATION_NOT_REJECTED: 409,
  RECONCILIATION_LIMIT_REACHED: 422,
  DEBT_CENTER_GROUP_LIMIT_REACHED: 422,
  DEBT_CENTER_PARTICIPANT_LIMIT_REACHED: 422,
  DEBT_CENTER_EXPENSE_LIMIT_REACHED: 422,
  DEBT_CENTER_DEBT_LIMIT_REACHED: 422,
  DEBT_CENTER_STATE_LIMIT_REACHED: 422,
  DEBT_CENTER_DATABASE_REQUIRED: 503,
  INVALID_DEBT_CENTER_STATE: 500,
  UNSUPPORTED_DEBT_CENTER_STATE_VERSION: 500,
};

const SAFE_MESSAGE_BY_CODE: Record<string, string> = {
  GROUP_NOT_FOUND: "No encontramos ese grupo demo.",
  EXPENSE_NOT_FOUND: "No encontramos ese gasto demo.",
  DEBT_NOT_FOUND: "Este cobro demo no existe o ya no está disponible.",
  PAYMENT_ATTEMPT_NOT_FOUND: "No encontramos ese intento de pago.",
  INVALID_EXPENSE: "Revisa el monto y selecciona al menos dos personas.",
  EXPENSE_AMOUNT_EXCEEDS_LIMIT: "Para esta demo, usa un monto de hasta $100.000.000.",
  INVALID_EXPENSE_COMMAND_ID: "No pudimos identificar este gasto demo. Vuelve a abrir el formulario.",
  INVALID_EXPENSE_CORRECTION_COMMAND_ID: "No pudimos identificar esta corrección demo. Vuelve a abrir el gasto.",
  INVALID_EXPENSE_CORRECTION_REASON: "Selecciona por qué necesitas corregir este gasto.",
  INVALID_EXPENSE_CORRECTION_SOURCE: "El gasto original cambió. Vuelve a abrir la corrección antes de crear la copia.",
  EXPENSE_CORRECTION_ALREADY_REPLACED: "Este gasto ya tiene una versión corregida. Abre la versión vigente para continuar.",
  EXPENSE_CORRECTION_GROUP_CHANGED: "La corrección debe permanecer en el mismo grupo. Crea otro gasto si necesitas moverla.",
  EXPENSE_CORRECTION_NOT_OWNED: "Sólo quien creó el gasto puede anularlo y preparar una corrección.",
  EXPENSE_ALREADY_CANCELLED_FOR_CORRECTION: "Este gasto ya fue anulado para corrección.",
  EXPENSE_CORRECTION_PAYMENT_IN_PROGRESS: "Hay un pago demo en curso. Termínalo antes de corregir este gasto.",
  EXPENSE_CORRECTION_HAS_PAYMENT: "Este gasto ya tiene un abono registrado. Para conservar la historia, no podemos reemplazarlo desde esta demo.",
  EXPENSE_CORRECTION_RECURRING_ACTIVE: "Detén primero el gasto habitual asociado antes de corregir esta versión.",
  INVALID_GROUP_COMMAND_ID: "No pudimos identificar este grupo demo. Vuelve a abrir el formulario.",
  INVALID_CLP_AMOUNT: "El monto debe ser un número entero de pesos.",
  DUPLICATE_PARTICIPANT: "Cada persona puede aparecer una sola vez en el reparto.",
  INVALID_SIMULATION_STATUS: "Ese resultado no existe en el simulador.",
  INVALID_EXPENSE_TITLE: "Escribe un nombre breve para el gasto.",
  INVALID_PAYMENT_AMOUNT: "El abono debe ser mayor que cero.",
  PAYMENT_EXCEEDS_OUTSTANDING: "El abono no puede superar lo que falta por pagar.",
  ACTIVE_PAYMENT_ATTEMPT_EXISTS: "Ya existe un pago abierto para esta deuda. Complétalo o ciérralo antes de crear otro.",
  DEBT_NOT_PAYABLE: "Esta deuda ya no admite pagos.",
  SPLIT_DOES_NOT_MATCH_TOTAL: "Los montos individuales deben sumar exactamente el total.",
  INVALID_SPLIT_MODE: "Ese tipo de reparto no está disponible.",
  INVALID_SPLIT_VALUES: "El reparto no tiene un formato válido.",
  SPLIT_VALUES_REQUIRED: "Completa el valor de cada persona antes de continuar.",
  SPLIT_VALUES_NOT_ALLOWED: "El reparto en partes iguales no necesita valores individuales.",
  SPLIT_VALUE_KEYS_MISMATCH: "El reparto debe incluir exactamente a las personas seleccionadas.",
  INVALID_SPLIT_WEIGHT: "Las partes del reparto no son válidas.",
  INVALID_PERCENTAGE_BPS: "Cada porcentaje debe estar entre 0% y 100% y usar hasta dos decimales.",
  PERCENTAGE_TOTAL_MUST_BE_10000: "Los porcentajes deben sumar exactamente 100%.",
  INVALID_SHARE_WEIGHT: "Las partes deben ser enteros desde cero y sumar más de cero.",
  SHARE_WEIGHT_LIMIT_EXCEEDED: "El número de partes supera el límite de esta demo.",
  PARTICIPANT_NOT_IN_GROUP: "Una de las personas no pertenece al grupo.",
  PAYER_MUST_PARTICIPATE: "La persona que pagó debe ser parte del reparto.",
  INVALID_GROUP_NAME: "Escribe un nombre para el grupo.",
  GROUP_NEEDS_PARTICIPANTS: "Agrega al menos una persona además de ti.",
  PARTICIPANT_NOT_FOUND: "No encontramos una de las personas seleccionadas.",
  SETTLED_PAYMENT_IS_FINAL: "Un abono confirmado no puede volver a un estado anterior.",
  STALE_PAYMENT_ATTEMPT: "El saldo cambió mientras se procesaba el pago. Actualiza e inténtalo nuevamente.",
  CONCURRENT_STATE_UPDATE: "Hubo otro cambio al mismo tiempo. Actualiza e inténtalo nuevamente.",
  IDEMPOTENCY_CONFLICT: "Este identificador ya se usó para otro monto.",
  PAYMENT_CREATION_IN_PROGRESS: "Este pago se está preparando. Espera un momento y actualiza.",
  INVALID_PAYMENT_STATUS_TRANSITION: "El pago ya llegó a un estado final y no puede retroceder.",
  TOO_MANY_PARTICIPANTS: "Este demo admite hasta 30 personas por grupo.",
  INVALID_IDEMPOTENCY_KEY: "El identificador de este intento demo no es válido.",
  INVALID_RECURRENCE_COMMAND_ID: "No pudimos identificar esta acción de gasto habitual.",
  INVALID_RECURRENCE_DATE: "Usa una fecha mensual válida entre los días 1 y 28.",
  RECURRING_TEMPLATE_NOT_FOUND: "No encontramos ese gasto habitual.",
  EXPENSE_ALREADY_RECURRING: "Ese gasto ya tiene una plantilla habitual activa.",
  RECURRING_TEMPLATE_NOT_ACTIVE: "Ese gasto habitual está pausado o archivado.",
  RECURRENCE_OCCURRENCE_STALE: "La siguiente fecha cambió. Actualiza antes de continuar.",
  RECURRENCE_OCCURRENCE_SKIPPED: "Esa ocurrencia fue omitida y no puede crearse después.",
  RECURRENCE_OCCURRENCE_ALREADY_MATERIALIZED: "Esa ocurrencia ya fue creada y no puede omitirse.",
  RECURRENCE_TEMPLATE_STALE: "El grupo o reparto cambió y esta plantilla necesita revisión.",
  RECURRING_TEMPLATE_LIMIT_REACHED: "La demo alcanzó su límite de gastos habituales.",
  RECURRENCE_OCCURRENCE_LIMIT_REACHED: "Ese gasto habitual alcanzó el límite de ocurrencias de la demo.",
  INVALID_COLLECTION_COMMAND_ID: "No pudimos identificar esta confirmación de cobro.",
  INVALID_COLLECTION_MESSAGE_KIND: "Ese tipo de mensaje de cobro no está disponible.",
  COLLECTION_NOT_OWNED: "Sólo quien recibe puede marcar este cobro como compartido.",
  DEBT_NOT_COLLECTABLE: "Esta cuenta ya no necesita un cobro.",
  COLLECTION_FOLLOW_UP_REQUIRES_INITIAL: "Primero confirma que compartiste el cobro inicial.",
  COLLECTION_CONFIRMATION_LIMIT_REACHED: "Esta demo alcanzó el límite de seguimientos guardados.",
  INVALID_RECONCILIATION_COMMAND_ID: "No pudimos identificar esta acción de conciliación demo.",
  INVALID_RECONCILIATION_FIXTURE: "Esa cartola ficticia no está disponible.",
  RECONCILIATION_CANDIDATE_NOT_FOUND: "No encontramos esa coincidencia demo.",
  RECONCILIATION_ENTRY_NOT_FOUND: "No encontramos ese movimiento de cartola demo.",
  RECONCILIATION_DECISION_NOT_FOUND: "No encontramos esa decisión de conciliación demo.",
  RECONCILIATION_NOT_OWNED: "Sólo quien recibe puede revisar esta cartola demo.",
  RECONCILIATION_CANDIDATE_STALE: "El saldo cambió. Revisa nuevamente antes de registrar el abono.",
  RECONCILIATION_ENTRY_ALREADY_USED: "Este movimiento demo ya respalda otra decisión vigente.",
  RECONCILIATION_PAYMENT_IN_PROGRESS: "Hay un pago simulado en curso para esta cuenta. Termínalo antes de conciliar.",
  RECONCILIATION_NOT_REJECTED: "Este movimiento no está descartado y no necesita reabrirse.",
  RECONCILIATION_LIMIT_REACHED: "La conciliación demo alcanzó su límite de movimientos o decisiones.",
  DEBT_CENTER_GROUP_LIMIT_REACHED: "Esta demo admite hasta 25 grupos.",
  DEBT_CENTER_PARTICIPANT_LIMIT_REACHED: "Esta demo admite hasta 100 personas en total.",
  DEBT_CENTER_EXPENSE_LIMIT_REACHED: "Esta demo admite hasta 250 gastos.",
  DEBT_CENTER_DEBT_LIMIT_REACHED: "Esta demo alcanzó el límite de cuentas pendientes.",
  DEBT_CENTER_STATE_LIMIT_REACHED: "Esta demo alcanzó su límite de almacenamiento. Reiníciala para continuar.",
  DEBT_CENTER_DATABASE_REQUIRED: "Cuentas Claras necesita persistencia Neon para funcionar en este entorno.",
  INVALID_DEBT_CENTER_STATE: "No pudimos recuperar el estado de esta demo.",
  UNSUPPORTED_DEBT_CENTER_STATE_VERSION: "Esta versión del estado demo todavía no es compatible.",
};

export function assertDebtCenterSimulatorEnabled() {
  if (process.env.NODE_ENV === "development" || process.env.DEBT_CENTER_SIMULATOR_ENABLED === "true") return;
  throw new PaymentProviderError("DEBT_CENTER_SIMULATOR_DISABLED", "El simulador de Cuentas Claras no está habilitado en este entorno.", 404);
}

export function debtCenterErrorResponse(error: unknown) {
  if (error instanceof PaymentProviderError) {
    const headers = new Headers(noStoreHeaders());
    if (error.retryAfterSeconds) headers.set("Retry-After", String(error.retryAfterSeconds));
    return Response.json({ ok: false, error: error.code, message: error.message }, { status: error.status, headers });
  }
  const code = error instanceof Error ? error.message : "UNKNOWN_ERROR";
  return Response.json({
    ok: false,
    error: code in SAFE_MESSAGE_BY_CODE ? code : "UNKNOWN_ERROR",
    message: SAFE_MESSAGE_BY_CODE[code] ?? "No pudimos completar la acción demo.",
  }, { status: STATUS_BY_CODE[code] ?? 500, headers: noStoreHeaders() });
}

export function noStoreHeaders() {
  return { "Cache-Control": "private, no-store, max-age=0", Pragma: "no-cache", Vary: "Cookie" };
}
